ebook_metadata:
  title: ༄༅། །བསྐྱེད་རིམ་གྱི་ཁྲིད་ཡིག་ཡང་ཡིག་ཟབ་པའི་མན་ངག་ཅེས་བྱ་བ་བཞུགས་སོ། །
  authors:
  - མཛད་པ་པོ། མཚུངས་མེད་གྲུབ་པའི་དབང་ཕྱུག་ཤཱཀྱ་ཤྲཱི་ཛྙཱ་ནའི་རྒྱལ་སྲས་འཕགས་མཆོག་རྡོ་རྗེ་མཆོག
  sku: KS-SP-04
  layers:
  - book_title
  - author
  - quotation
  - sabche
web_metadata:
  title:
    en: Profound Ancillary Instructions for the Practice of the Creation Phase Yoga
    bo: བསྐྱེད་རིམ་གྱི་ཁྲིད་ཡིག་ཡང་ཡིག་ཟབ་པའི་མན་ངག་ཅེས་བྱ་བ་བཞུགས་སོ།།
  collection:
    en: Se Phakchok Series–  Book 4
    bo: སྲས་འཕགས་མཆོག།–  དེབ། ༤
  author:
    en: Authors:Phakchok Dorje
    bo: འཕགས་མཆོག་རྡོ་རྗེ།
  pusblisher:
    en: Gautam Buddha Vihara
    bo: དོན་བརྒྱུད་དཔལ་ལྡན་འབྲུག་པ།
  sku: KS-SP-04
  category:
    en: ''
    bo: ''
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: KS-SP-04.epub
  description:
    en: ''
    bo: ''
